global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      # targets for rbp's. port 8080 is used main.py
    - targets: ["localhost:8080","raspberrypi.local:8080",]

